baseURL = 'https://blog-website-weld-beta.vercel.app/'
languageCode = 'en-us'
title = "Amodh's Blog"

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"